%Project Euler #2
%Each new term in the Fibonacci sequence is generated by adding the 
%previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
%1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%By considering the terms in the Fibonacci sequence whose values do not 
%exceed four million, find the sum of the even-valued terms.


clear all
a=1;
b=2;
c=0;
i=1;
sum=0;
n=4000000;
while c<n
    c=a+b;
    if i==1
        sum=sum+b;
    end
    a=b;
    b=c;
    i=i+1;
    if i==4
        i=1;
    end
end