% Project Euler #45

% Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

% Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
% Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
% Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
% It can be verified that T285 = P165 = H143 = 40755.

% Find the next triangle number that is also pentagonal and hexagonal.

clear all
clc
format('longe')

a=286;
z=0;
while z==0
    % First Calculate Triangle number
    T=a*(a+1)/2;
    % Second find the roots using the Pentagonal Eqn.
    % Round and use the max (eliminating negative root).
    b= max(round(roots([3 -1 -2*T])));
    % Third find the roots using the Hexagonal Eqn.
    % Round and take max (eliminating negative root).    
    c= max(round(roots([2 -1 -T])));
    % Calculate Pb from rounded root
    P=b*(3*b-1)/2;
    % Calculate Hc from rounded root
    H=c*(2*c-1);
    % Determine if all values are equal
    if T == P
        if P==H
            % If equal, kick out of loop
            z=1;
        end
    end
    if z==0
        % If not equal, increment to next index for T
        a=a+1;
    end
end

final = num2str(T)
