% Project Euler #29
% Consider all integer combinations of ab for 2 ? a ? 5 and 2 ? b ? 5:
% 
% 2^2=4, 2^3=8, 2^4=16, 2^5=32
% 3^2=9, 3^3=27, 3^4=81, 3^5=243
% 4^2=16, 4^3=64, 4^4=256, 4^5=1024
% 5^2=25, 5^3=125, 5^4=625, 5^5=3125
% If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
% 
% 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
% 
% How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?
clear all
clc

% Determine the Maximum number of distinct powers:

max = 99 * 99;
count = 0;
remain = [];

% Then determine what numbers will have repeats.

for a=[2:100]
    d=0;
    for c=[2:6]
        if a^c <101
            remain=[remain;a^c,a,c];
            d=1;
        end
    end
    if d==0
        count = count + 99;
    end
end

x=0
rem2=[];
for i=[1:length(remain(:,1))]
    a=remain(i,1);
    b=remain(i,2);
    c=remain(i,3);
    newcount=0;
    if isprime(c)==1
        for d=[2:100]
            if d*c <= 100
                newcount = newcount;
            else
                newcount=newcount +1;
            end
        end
        x=x+newcount;
    else
        rem2=[rem2;a,b,c]
    end
end

count = count + x;
